/*
5/2/2022: 389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
class FindDifference {
    public char findTheDifference(String s, String t) {
        int resultS = 0;
        int resultT = 0;
        int i;
    for(i = 0; i < s.length(); i++){
        resultS += (int) s.charAt(i);
        resultT += (int) t.charAt(i);
    }
        resultT += (int) t.charAt(i);
        return (char)(resultT - resultS);
    }
}
